id: I1E6D1E94
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:53:19+00:00'
last_modified: '2022-06-08T09:59:21.987985+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1104
  title: ལྷ་མོ་དབྱངས་ཅན་མ་ལ་བསྟོད་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4E60:
      image_group_id: I1CZ1370
      title: ''
      total_pages: 10
      order: 1
      base_file: 4E60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
