id: P009293
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:57.114641
source_metadata:
  id: bdr:W1CZ1104
  title: ལྷ་མོ་དབྱངས་ཅན་མ་ལ་བསྟོད་པ
  author: ''
  volumes:
    e8960ea1013b40989d146399cbff3541:
      image_group_id: I1CZ1370
      title: ''
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
